-- AlterEnum
ALTER TYPE "ExtraChargeType" ADD VALUE IF NOT EXISTS 'DISCOUNT_PERCENT';
ALTER TYPE "ExtraChargeType" ADD VALUE IF NOT EXISTS 'DISCOUNT_FIXED';

-- AlterTable
ALTER TABLE "Product"
ADD COLUMN "costUsd" DECIMAL(12,2);
