-- Amplia las condiciones fiscales del receptor para facturacion ARCA.
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'MONOTRIBUTO_SOCIAL';
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'MONOTRIBUTO_TRABAJADOR_INDEPENDIENTE_PROMOVIDO';
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'IVA_SUJETO_EXENTO';
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'IVA_NO_ALCANZADO';
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'SUJETO_NO_CATEGORIZADO';
ALTER TYPE "CustomerFiscalTaxProfile" ADD VALUE IF NOT EXISTS 'IVA_LIBERADO';
